server:
  port: 8082

spring:
  application:
    name: cart
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 上线打开缓存
  redis:
    host: localhost
  session:
    store-type: redis

sso:
  server:
    url: http://127.0.0.1:8080/login.html