server:
  port: 8080

spring:
  application:
    name: cart
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false # 上线打开缓存
  redis:
    host: localhost
  session:
    store-type: redis